version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install boto3
  build:
    commands:
      - python $CODEBUILD_SRC_DIR_herramientas/transformar.py
  post_build:
    commands:
      - echo "--- CONTENIDO DEL JAVA GENERADO ---"
      - cat resultado_operacion.cbl.md
      - echo "--- FIN DEL ARCHIVO ---"
